apiVersion: v1
kind: Secret
metadata:
  name: talos-credentials
  namespace: kangal-patch
type: Opaque
stringData:
  # Base64-encoded CA certificate
  ca.crt: LS0tLS1CRUdJTi...
  # Base64-encoded client certificate
  tls.crt: LS0tLS1CRUdJTi...
  # Base64-encoded client key
  tls.key: LS0tLS1CRUdJTi...
